version: "3.2"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: smart_health_care_system_web
    command: bash -c "npm run server:prod"
    ports:
      - "5000:5000"
    depends_on:
      - db
    restart: always
    env_file: .env

  db:
    image: mongo
    # If u change the name of the container,
    # you must change the name of the mongo_uri
    # in env variable
    container_name: smart_health_care_system_db
    env_file: .env
    volumes:
      - smart-health-care-system-mongo:/data/db
    restart: always

volumes:
  smart-health-care-system-mongo:
