version: "3.2"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: smart_health_care_system_web

    volumes:
      - type: bind
        source: ./
        target: /app

    # Initialize cron-jobs in the background
    # Start the production server
    command: bash -c "npm run server:prod"
    ports:
      - "5000:5000"
    depends_on:
      - db
    restart: always
    env_file: .env

  db:
    image: mongo
    container_name: smart_health_care_system_db
    env_file: .env
    volumes:
      - smart-health-care-system-mongo:/data/db
    restart: always

volumes:
  smart-health-care-system-mongo:
